/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_180001000(__int64 a1, __int64 a2, char a3, __int16 a4, __int64 a5, int a6);
_QWORD *__fastcall sub_1800010B0(_QWORD *a1, char a2);
bool __fastcall sub_1800010F0(__int64 a1, unsigned int a2, __int64 a3);
bool __fastcall sub_180001130(__int64 a1, __int64 a2, int a3);
const char *sub_180001150();
__int64 __fastcall sub_180001160(__int64 a1, __int64 a2, int a3);
const char *sub_1800011D0();
__int64 __fastcall sub_1800011E0(__int64 a1, __int64 a2, int a3);
const char *sub_180001230();
__int64 __fastcall sub_180001240(__int64 a1, __int64 a2, int a3);
__int64 __fastcall sub_1800012B0(__int64 a1, __int64 a2, int a3);
int sub_1800012F0();
int __fastcall sub_180001370(__int64 a1, SOCKET *a2, const char *a3, u_short a4);
__int64 __fastcall sub_180001640(__int64 a1, int a2, _BYTE *a3, int a4);
__int64 __fastcall sub_180001850(__int64 a1, int a2);
__int64 __fastcall sub_180001940(__int64 a1, int a2, const char *a3, int a4);
__int64 __fastcall sub_1800019B0(__int64 a1, int a2, char *a3, int a4);
__int64 __fastcall sub_180001A60(__int64 **a1);
void **__fastcall sub_180001AB0(void **a1, char *Src, size_t Size);
void **__fastcall sub_180001C00(void **a1, void **a2, unsigned __int64 a3, size_t a4);
bool __fastcall sub_180001CE0(const void **a1, unsigned __int64 a2);
_QWORD *__fastcall sub_180001D50(_QWORD *a1, __int64 a2, unsigned __int64 a3);
void __fastcall sub_180001E00(const void **Src, unsigned __int64 a2, size_t a3);
__int64 __fastcall sub_180001F10(__int64 a1, _BYTE *a2);
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
__int64 __fastcall FMC4030_Open_Device(__int64 a1, _BYTE *a2, int a3);
__int64 __fastcall FMC4030_Close_Device(__int64 a1);
__int64 __fastcall FMC4030_Jog_Single_Axis(int a1, char a2, float a3, float a4, int a5, int a6, char a7);
__int64 __fastcall FMC4030_Get_Machine_Status(int a1, _DWORD *a2);
__int64 __fastcall FMC4030_Get_Device_Para(int a1, __int64 a2);
__int64 __fastcall FMC4030_Set_Device_Para(int a1, __int64 a2);
__int64 __fastcall FMC4030_Check_Axis_Is_Stop(int a1, int a2);
__int64 __fastcall FMC4030_Home_Single_Axis(int a1, char a2, float a3, float a4, int a5, char a6);
__int64 __fastcall FMC4030_Stop_Single_Axis(int a1, int a2, char a3);
__int64 __fastcall FMC4030_Get_Axis_Current_Pos(int a1, char a2, __int64 a3);
__int64 __fastcall FMC4030_Get_Axis_Current_Speed(int a1, char a2, __int64 a3);
__int64 __fastcall FMC4030_Set_Output(int a1, int a2, char a3);
__int64 __fastcall FMC4030_Get_Input(int a1, int a2, _DWORD *a3);
__int64 __fastcall FMC4030_Write_Data_To_485(int a1, const void *a2, int a3);
__int64 __fastcall FMC4030_Read_Data_From_485(int a1, void *a2, int *a3);
__int64 __fastcall FMC4030_Line_2Axis(int a1, int a2, float a3, float a4, int a5, int a6, int a7);
__int64 __fastcall FMC4030_Line_3Axis(int a1, int a2, float a3, float a4, int a5, int a6, int a7, int a8);
__int64 __fastcall FMC4030_Arc_2Axis(int a1, int a2, float a3, float a4, int a5, int a6, int a7, int a8, int a9, int a10, char a11);
__int64 __fastcall FMC4030_Pause_Run(int a1, char a2);
__int64 __fastcall FMC4030_Resume_Run(int a1, char a2);
__int64 FMC4030_Stop_Run();
__int64 __fastcall FMC4030_Download_File(int a1, const char *a2, int a3);
__int64 __fastcall FMC4030_Start_Auto_Run(int a1, _BYTE *a2);
__int64 __fastcall FMC4030_Stop_Auto_Run(int a1);
__int64 __fastcall FMC4030_Delete_Script_File(int a1, _BYTE *a2);
__int64 __fastcall FMC4030_Get_Version_Info(int a1, __int64 a2);
__int64 __fastcall FMC4030_MB03_Operation(int a1, unsigned __int8 a2, __int16 a3, int a4, void *a5, _DWORD *a6);
__int64 __fastcall FMC4030_MB05_Operation(int a1, unsigned __int8 a2, __int16 a3, __int16 a4, void *a5, _DWORD *a6);
__int64 __fastcall FMC4030_MB06_Operation(int a1, unsigned __int8 a2, __int16 a3, __int16 a4, void *a5, _DWORD *a6);
__int64 __fastcall FMC4030_MB16_Operation(int a1, char a2, __int16 a3, int a4, __int64 a5, void *a6, _DWORD *a7);
__int64 __fastcall sub_1800043F0(unsigned __int8 *a1, unsigned int a2);
// int __cdecl atexit(void (__cdecl *)());
void sub_180004E28();
void __fastcall sub_180004E60();
void __fastcall sub_180004EA4();
// __int64 __fastcall _clean_type_info_names_internal(_QWORD); weak
// void __stdcall __noreturn CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo);
// void *__cdecl memcpy(void *, const void *Src, size_t Size);
// void *__cdecl memset(void *, int Val, size_t Size);
int sub_180005120();
int sub_180005130();
int sub_180005140();
int sub_180005150();
int sub_180005160();
int sub_180005170();
void **sub_180005180();
void **sub_180005190();
void **sub_1800051A0();
int sub_1800051B0(); // idb
__int64 __fastcall nullsub_1(); // weak
__int64 __fastcall nullsub_2(); // weak
// __int64 __fastcall std::ios::setstate(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD); weak
// __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD); weak
// __int64 __fastcall std::ostream::flush(_QWORD, _QWORD); weak
// __int64 __fastcall std::ostream::_Osfx(_QWORD); weak
// __int64 __fastcall std::streambuf::sputn(_QWORD, _QWORD, _QWORD); weak
// void std::_Xbad_alloc(void); weak
// void __stdcall __noreturn std::_Xlength_error(const char *); weak
// void __stdcall std::_Xout_of_range(const char *); weak
// bool std::uncaught_exception(void); weak
// const char *__stdcall std::_Winerror_map(_DWORD); weak
// const char *__stdcall std::_Syserror_map(_DWORD); weak
// __int64 __fastcall std::streambuf::sputc(_QWORD, _QWORD); weak
// void __stdcall operator delete(void *); weak
// void __stdcall operator delete[](void *); weak
// void *__stdcall operator new[](unsigned __int64); weak
// void *__stdcall operator new(unsigned __int64); weak

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN std::endl; weak
// extern _UNKNOWN std::cout; weak
// extern int (__cdecl *fclose)(FILE *Stream);
// extern size_t (__cdecl *fread)(void *Buffer, size_t ElementSize, size_t ElementCount, FILE *Stream);
// extern int (__cdecl *ftell)(FILE *Stream);
// extern int (__cdecl *fseek)(FILE *Stream, int Offset, int Origin);
// extern errno_t (__cdecl *fopen_s)(FILE **Stream, const char *FileName, const char *Mode);
// extern void *(__cdecl *memmove)(void *, const void *Src, size_t Size);
// extern int (__stdcall *_WSAFDIsSet)(SOCKET fd, fd_set *);
// extern int (__stdcall *send)(SOCKET s, const char *buf, int len, int flags);
// extern int (__stdcall *recv)(SOCKET s, char *buf, int len, int flags);
// extern int (__stdcall *WSAGetLastError)();
// extern int (__stdcall *connect)(SOCKET s, const struct sockaddr *name, int namelen);
// extern int (__stdcall *ioctlsocket)(SOCKET s, int cmd, u_long *argp);
// extern int (__stdcall *setsockopt)(SOCKET s, int level, int optname, const char *optval, int optlen);
// extern int (__stdcall *getsockopt)(SOCKET s, int level, int optname, char *optval, int *optlen);
// extern u_short (__stdcall *htons)(u_short hostshort);
// extern unsigned int (__stdcall *inet_addr)(const char *cp);
// extern SOCKET (__stdcall *socket)(int af, int type, int protocol);
// extern int (__stdcall *WSAStartup)(WORD wVersionRequested, LPWSADATA lpWSAData);
// extern int (__stdcall *WSACleanup)();
// extern int (__stdcall *shutdown)(SOCKET s, int how);
// extern int (__stdcall *closesocket)(SOCKET s);
// extern int (__stdcall *select)(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, const struct timeval *timeout);
void *std::error_category::`vftable' = &sub_1800010B0; // weak
void (*qword_1800068B8[2])(void) = { NULL, NULL }; // weak
void (*qword_1800068C8)(void) = NULL; // weak
__int64 (__fastcall **off_180008110[3])() = { &off_180006490, &off_180006458, &off_180006420 }; // weak
__int64 (__fastcall **off_180008118[2])() = { &off_180006458, &off_180006420 }; // weak
__int64 (__fastcall **off_180008120)() = &off_180006420; // weak
_UNKNOWN unk_1800086B8; // weak
__int64 qword_1800086D8; // weak


//----- (0000000180001000) ----------------------------------------------------
__int64 __fastcall sub_180001000(__int64 a1, __int64 a2, char a3, __int16 a4, __int64 a5, int a6)
{
  __int64 v7; // rax
  __int64 v8; // r8
  __int64 v9; // rcx
  char v10; // dl
  __int16 v11; // cx
  __int64 v12; // r11
  int v13; // r10d
  __int64 result; // rax

  *(_WORD *)a2 = 7937;
  *(_BYTE *)(a2 + 2) = a3;
  *(_BYTE *)(a2 + 4) = HIBYTE(a4);
  *(_BYTE *)(a2 + 3) = 16;
  *(_BYTE *)(a2 + 5) = a4;
  *(_BYTE *)(a2 + 7) = a6;
  *(_BYTE *)(a2 + 6) = BYTE1(a6);
  *(_BYTE *)(a2 + 8) = 2 * a6;
  if ( a6 > 0 )
  {
    v7 = a5;
    v8 = (unsigned int)a6;
    v9 = a2 - a5;
    do
    {
      v10 = *(_BYTE *)(v7 + 1);
      v7 += 2i64;
      *(_BYTE *)(v9 + v7 + 7) = v10;
      *(_BYTE *)(v9 + v7 + 8) = *(_BYTE *)(v7 - 2);
      --v8;
    }
    while ( v8 );
  }
  v11 = sub_1800043F0((unsigned __int8 *)(a2 + 2), 2 * a6 + 7);
  *(_BYTE *)(v12 + 2i64 * a6 + 10) = v11;
  result = (unsigned int)(v13 + 11);
  *(_BYTE *)(v12 + 2i64 * a6 + 9) = HIBYTE(v11);
  return result;
}
// 18000108D: variable 'v12' is possibly undefined
// 180001092: variable 'v13' is possibly undefined

//----- (00000001800010B0) ----------------------------------------------------
_QWORD *__fastcall sub_1800010B0(_QWORD *a1, char a2)
{
  *a1 = &std::error_category::`vftable';
  if ( (a2 & 1) != 0 )
    operator delete(a1);
  return a1;
}
// 180006108: using guessed type void __stdcall operator delete(void *);
// 1800064C8: using guessed type void *std::error_category::`vftable';

//----- (00000001800010F0) ----------------------------------------------------
bool __fastcall sub_1800010F0(__int64 a1, unsigned int a2, __int64 a3)
{
  __int64 v4; // rax
  char v6[24]; // [rsp+20h] [rbp-18h] BYREF

  v4 = (*(__int64 (__fastcall **)(__int64, char *, _QWORD))(*(_QWORD *)a1 + 24i64))(a1, v6, a2);
  return *(_QWORD *)(v4 + 8) == *(_QWORD *)(a3 + 8) && *(_DWORD *)v4 == *(_DWORD *)a3;
}
// 1800010F0: using guessed type char var_18[24];

//----- (0000000180001130) ----------------------------------------------------
bool __fastcall sub_180001130(__int64 a1, __int64 a2, int a3)
{
  return a1 == *(_QWORD *)(a2 + 8) && *(_DWORD *)a2 == a3;
}

//----- (0000000180001150) ----------------------------------------------------
const char *sub_180001150()
{
  return "generic";
}

//----- (0000000180001160) ----------------------------------------------------
__int64 __fastcall sub_180001160(__int64 a1, __int64 a2, int a3)
{
  size_t v3; // rbx
  const char *v5; // rax
  char *v6; // rdx

  v3 = 0i64;
  v5 = std::_Syserror_map(a3);
  *(_QWORD *)(a2 + 24) = 15i64;
  *(_QWORD *)(a2 + 16) = 0i64;
  v6 = "unknown error";
  if ( v5 )
    v6 = (char *)v5;
  *(_BYTE *)a2 = 0;
  if ( *v6 )
  {
    v3 = -1i64;
    do
      ++v3;
    while ( v6[v3] );
  }
  sub_180001AB0((void **)a2, v6, v3);
  return a2;
}
// 1800060B0: using guessed type const char *__stdcall std::_Syserror_map(_DWORD);

//----- (00000001800011D0) ----------------------------------------------------
const char *sub_1800011D0()
{
  return "iostream";
}

//----- (00000001800011E0) ----------------------------------------------------
__int64 __fastcall sub_1800011E0(__int64 a1, __int64 a2, int a3)
{
  if ( a3 == 1 )
  {
    *(_QWORD *)(a2 + 24) = 15i64;
    *(_QWORD *)(a2 + 16) = 0i64;
    *(_BYTE *)a2 = 0;
    sub_180001AB0((void **)a2, "iostream stream error", 0x15ui64);
  }
  else
  {
    sub_180001160(a1, a2, a3);
  }
  return a2;
}

//----- (0000000180001230) ----------------------------------------------------
const char *sub_180001230()
{
  return "system";
}

//----- (0000000180001240) ----------------------------------------------------
__int64 __fastcall sub_180001240(__int64 a1, __int64 a2, int a3)
{
  size_t v3; // rbx
  const char *v5; // rax
  char *v6; // rdx

  v3 = 0i64;
  v5 = std::_Winerror_map(a3);
  *(_QWORD *)(a2 + 24) = 15i64;
  *(_QWORD *)(a2 + 16) = 0i64;
  v6 = "unknown error";
  if ( v5 )
    v6 = (char *)v5;
  *(_BYTE *)a2 = 0;
  if ( *v6 )
  {
    v3 = -1i64;
    do
      ++v3;
    while ( v6[v3] );
  }
  sub_180001AB0((void **)a2, v6, v3);
  return a2;
}
// 1800060A8: using guessed type const char *__stdcall std::_Winerror_map(_DWORD);

//----- (00000001800012B0) ----------------------------------------------------
__int64 __fastcall sub_1800012B0(__int64 a1, __int64 a2, int a3)
{
  const char *v5; // rax
  bool v6; // zf
  __int64 (__fastcall ***v7)(); // rax

  v5 = std::_Syserror_map(a3);
  *(_DWORD *)a2 = a3;
  v6 = v5 == 0i64;
  v7 = off_180008110;
  if ( v6 )
    v7 = &off_180008120;
  *(_QWORD *)(a2 + 8) = v7;
  return a2;
}
// 1800060B0: using guessed type const char *__stdcall std::_Syserror_map(_DWORD);
// 180008110: using guessed type __int64 (__fastcall **off_180008110[3])();
// 180008120: using guessed type __int64 (__fastcall **off_180008120)();

//----- (00000001800012F0) ----------------------------------------------------
int sub_1800012F0()
{
  __int64 i; // rax

  for ( i = qword_1800086D8; qword_1800086D8; i = qword_1800086D8 )
  {
    if ( *(_DWORD *)(i + 24) == 2 )
    {
      closesocket(*(_QWORD *)(i + 32));
      shutdown(*(_QWORD *)(qword_1800086D8 + 32), 2);
      *(_DWORD *)(qword_1800086D8 + 24) = 1;
      i = qword_1800086D8;
    }
    qword_1800086D8 = *(_QWORD *)(i + 40);
    operator delete((void *)i);
  }
  return WSACleanup();
}
// 180006108: using guessed type void __stdcall operator delete(void *);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180001370) ----------------------------------------------------
int __fastcall sub_180001370(__int64 a1, SOCKET *a2, const char *a3, u_short a4)
{
  int result; // eax
  u_short v8; // ax
  SOCKET v9; // rcx
  SOCKET v10; // rcx
  SOCKET v11; // rcx
  __int64 v12; // rax
  SOCKET v13; // rcx
  int v14; // ecx
  int v15; // eax
  __int64 v16; // rax
  __int64 v17; // rax
  __int64 v18; // rax
  u_long argp; // [rsp+30h] [rbp-D0h] BYREF
  int optlen; // [rsp+34h] [rbp-CCh] BYREF
  char optval[8]; // [rsp+38h] [rbp-C8h] BYREF
  struct timeval timeout; // [rsp+40h] [rbp-C0h] BYREF
  struct sockaddr name; // [rsp+48h] [rbp-B8h] BYREF
  fd_set writefds; // [rsp+60h] [rbp-A0h] BYREF
  fd_set readfds; // [rsp+270h] [rbp+170h] BYREF
  struct WSAData WSAData; // [rsp+480h] [rbp+380h] BYREF

  if ( WSAStartup(0x202u, &WSAData) )
    return -1;
  if ( WSAData.wVersion == 514 )
  {
    *a2 = socket(2, 1, 0);
    *(_DWORD *)&name.sa_data[2] = inet_addr(a3);
    name.sa_family = 2;
    v8 = htons(a4);
    v9 = *a2;
    *(_WORD *)name.sa_data = v8;
    optlen = 4;
    getsockopt(v9, 0xFFFF, 4097, optval, &optlen);
    v10 = *a2;
    optlen = 1024;
    setsockopt(v10, 0xFFFF, 4097, optval, 1024);
    v11 = *a2;
    argp = 1;
    if ( ioctlsocket(v11, -2147195266, &argp) == -1 )
    {
      v12 = sub_180001F10(std::cout, "Socket Set FIONBIO Fail");
      std::ostream::operator<<(v12, std::endl);
      closesocket(*a2);
      return -3;
    }
    v13 = *a2;
    timeout = (struct timeval)1i64;
    if ( connect(v13, &name, 16) )
    {
      result = WSAGetLastError();
      if ( result != 10035 )
        return result;
      v14 = *a2 + 1;
      readfds.fd_array[0] = *a2;
      writefds.fd_array[0] = readfds.fd_array[0];
      readfds.fd_count = 1;
      writefds.fd_count = 1;
      v15 = select(v14, &readfds, &writefds, 0i64, &timeout);
      if ( v15 < 0 )
      {
        v16 = sub_180001F10(std::cout, "Select Fail");
        std::ostream::operator<<(v16, std::endl);
LABEL_10:
        closesocket(*a2);
        return -4;
      }
      if ( !v15 )
      {
        v17 = sub_180001F10(std::cout, "Connect Timeout");
        std::ostream::operator<<(v17, std::endl);
LABEL_13:
        closesocket(*a2);
        return -5;
      }
      if ( !_WSAFDIsSet(*a2, &writefds) )
        goto LABEL_13;
      argp = 0;
      v18 = sub_180001F10(std::cout, "Select Success");
      std::ostream::operator<<(v18, std::endl);
      if ( ioctlsocket(*a2, -2147195266, &argp) )
        goto LABEL_10;
    }
    return 0;
  }
  else
  {
    WSACleanup();
    return -2;
  }
}
// 180006058: using guessed type __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 180001370: using guessed type char optval[8];

//----- (0000000180001640) ----------------------------------------------------
__int64 __fastcall sub_180001640(__int64 a1, int a2, _BYTE *a3, int a4)
{
  __int64 v4; // rbx
  __int64 v8; // r10
  unsigned __int8 *v10; // rax
  char *v11; // r8
  int v12; // ecx
  int v13; // edx
  unsigned __int8 *v14; // rax
  int v15; // ecx
  int v16; // edx
  char *v17; // rsi
  size_t v18; // r8
  __int64 v19; // rcx
  unsigned int v20; // edi
  __int64 v21; // rax
  __int64 v22; // rax
  _DWORD *v23; // rbx
  size_t v24; // r8
  __int64 v25; // rcx
  unsigned int v26; // edi
  __int64 v27; // rax

  v4 = qword_1800086D8;
  if ( qword_1800086D8 )
  {
    v8 = *(_QWORD *)(qword_1800086D8 + 40);
    if ( *(_DWORD *)qword_1800086D8 == a2 )
      return 4294967292i64;
    v10 = (unsigned __int8 *)(qword_1800086D8 + 4);
    v11 = &a3[-qword_1800086D8 - 4];
    do
    {
      v12 = (unsigned __int8)v11[(_QWORD)v10];
      v13 = *v10 - v12;
      if ( v13 )
        break;
      ++v10;
    }
    while ( v12 );
    if ( !v13 && *(_DWORD *)(qword_1800086D8 + 20) == a4 )
      return 4294967291i64;
    if ( v8 )
    {
      while ( *(_DWORD *)v8 != a2 )
      {
        v14 = (unsigned __int8 *)(v8 + 4);
        do
        {
          v15 = (unsigned __int8)a3[(_QWORD)v14 - 4 - v8];
          v16 = *v14 - v15;
          if ( v16 )
            break;
          ++v14;
        }
        while ( v15 );
        if ( !v16 && *(_DWORD *)(v8 + 20) == a4 )
          return 4294967291i64;
        v8 = *(_QWORD *)(v8 + 40);
        v4 = *(_QWORD *)(v4 + 40);
        if ( !v8 )
          goto LABEL_18;
      }
      return 4294967292i64;
    }
LABEL_18:
    v17 = (char *)operator new(0x30ui64);
    *(_DWORD *)v17 = a2;
    v18 = -1i64;
    *(_QWORD *)(v17 + 4) = 0i64;
    *((_DWORD *)v17 + 3) = 0;
    *((_WORD *)v17 + 8) = 0;
    v17[18] = 0;
    do
      ++v18;
    while ( a3[v18] );
    memcpy(v17 + 4, a3, v18);
    *((_DWORD *)v17 + 5) = a4;
    v20 = sub_180001370(v19, (SOCKET *)v17 + 4, v17 + 4, a4);
    if ( v20 )
    {
      v21 = sub_180001F10(std::cout, "add device failed: ");
      v22 = std::ostream::operator<<(v21, v20);
      std::ostream::operator<<(v22, std::endl);
      operator delete(v17);
      return v20;
    }
    *((_DWORD *)v17 + 6) = 2;
    *((_QWORD *)v17 + 5) = 0i64;
    *(_QWORD *)(v4 + 40) = v17;
  }
  else
  {
    v23 = operator new(0x30ui64);
    v24 = -1i64;
    *(_QWORD *)(v23 + 1) = 0i64;
    v23[3] = 0;
    *((_WORD *)v23 + 8) = 0;
    *((_BYTE *)v23 + 18) = 0;
    *v23 = a2;
    do
      ++v24;
    while ( a3[v24] );
    memcpy(v23 + 1, a3, v24);
    v23[5] = a4;
    *((_QWORD *)v23 + 5) = 0i64;
    v26 = sub_180001370(v25, (SOCKET *)v23 + 4, a3, a4);
    if ( v26 )
    {
      v27 = sub_180001F10(std::cout, "add device failed");
      std::ostream::operator<<(v27, std::endl);
      operator delete(v23);
      return v26;
    }
    v23[6] = 2;
    qword_1800086D8 = (__int64)v23;
  }
  return 0i64;
}
// 180001737: variable 'v19' is possibly undefined
// 1800017EB: variable 'v25' is possibly undefined
// 180006058: using guessed type __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 180006060: using guessed type __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 180006108: using guessed type void __stdcall operator delete(void *);
// 1800061B8: using guessed type void *__stdcall operator new(unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180001850) ----------------------------------------------------
__int64 __fastcall sub_180001850(__int64 a1, int a2)
{
  __int64 v2; // rsi
  _QWORD *v4; // rbx
  __int64 v5; // rdi

  v2 = qword_1800086D8;
  if ( !qword_1800086D8 )
    return 0xFFFFFFFFi64;
  v4 = *(_QWORD **)(qword_1800086D8 + 40);
  if ( *(_DWORD *)qword_1800086D8 == a2 )
  {
    if ( *(_DWORD *)(qword_1800086D8 + 24) == 2 )
    {
      closesocket(*(_QWORD *)(qword_1800086D8 + 32));
      shutdown(*(_QWORD *)(v2 + 32), 2);
      *(_DWORD *)(v2 + 24) = 1;
    }
    operator delete((void *)v2);
    qword_1800086D8 = (__int64)v4;
    return 0i64;
  }
  else if ( v4 )
  {
    while ( *(_DWORD *)v4 != a2 )
    {
      v4 = (_QWORD *)v4[5];
      v2 = *(_QWORD *)(v2 + 40);
      if ( !v4 )
        return 4294967294i64;
    }
    if ( *((_DWORD *)v4 + 6) == 2 )
    {
      closesocket(v4[4]);
      shutdown(v4[4], 2);
      *((_DWORD *)v4 + 6) = 1;
    }
    v5 = v4[5];
    operator delete(v4);
    *(_QWORD *)(v2 + 40) = v5;
    return 0i64;
  }
  else
  {
    return 4294967294i64;
  }
}
// 180006108: using guessed type void __stdcall operator delete(void *);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180001940) ----------------------------------------------------
__int64 __fastcall sub_180001940(__int64 a1, int a2, const char *a3, int a4)
{
  __int64 v4; // rcx

  v4 = qword_1800086D8;
  if ( !qword_1800086D8 )
    return 4294967294i64;
  while ( *(_DWORD *)v4 != a2 )
  {
    v4 = *(_QWORD *)(v4 + 40);
    if ( !v4 )
      return 4294967292i64;
  }
  if ( *(_DWORD *)(v4 + 24) == 2 )
    return (unsigned int)(send(*(_QWORD *)(v4 + 32), a3, a4, 0) != -1) - 1;
  else
    return 4294967293i64;
}
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800019B0) ----------------------------------------------------
__int64 __fastcall sub_1800019B0(__int64 a1, int a2, char *a3, int a4)
{
  __int64 v4; // rbx
  unsigned int v5; // edi
  int v9; // eax

  v4 = qword_1800086D8;
  v5 = 0;
  if ( !qword_1800086D8 )
    return 4294967294i64;
  while ( *(_DWORD *)v4 != a2 )
  {
    v4 = *(_QWORD *)(v4 + 40);
    if ( !v4 )
      return 4294967292i64;
  }
  if ( *(_DWORD *)(v4 + 24) != 2 )
    return 4294967293i64;
  v9 = recv(*(_QWORD *)(v4 + 32), a3, a4, 0);
  if ( v9 == -1 )
    return 0xFFFFFFFFi64;
  while ( 1 )
  {
    v5 += v9;
    if ( v5 == a4 )
      break;
    v9 = recv(*(_QWORD *)(v4 + 32), &a3[v5], a4, 0);
    if ( v9 == -1 )
      return 0xFFFFFFFFi64;
  }
  return v5;
}
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180001A60) ----------------------------------------------------
__int64 __fastcall sub_180001A60(__int64 **a1)
{
  __int64 result; // rax
  __int64 v3; // rcx

  if ( !std::uncaught_exception() )
    std::ostream::_Osfx(*a1);
  result = **a1;
  v3 = *(__int64 *)((char *)*a1 + *(int *)(result + 4) + 72);
  if ( v3 )
    return (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v3 + 16i64))(v3);
  return result;
}
// 180006070: using guessed type __int64 __fastcall std::ostream::_Osfx(_QWORD);
// 180006098: using guessed type bool std::uncaught_exception(void);

//----- (0000000180001AB0) ----------------------------------------------------
void **__fastcall sub_180001AB0(void **a1, char *Src, size_t Size)
{
  void **v5; // rbx
  unsigned __int64 v6; // rdx
  char *v7; // rax
  _BYTE *v8; // rax
  void **result; // rax
  size_t v10; // rax
  void *v11; // rcx
  bool v12; // cf
  _BYTE *v13; // rax

  v5 = a1;
  if ( !Src )
    goto LABEL_13;
  v6 = (unsigned __int64)a1[3];
  v7 = v6 < 0x10 ? (char *)a1 : (char *)*a1;
  if ( Src < v7 )
    goto LABEL_13;
  if ( v6 >= 0x10 )
    a1 = (void **)*a1;
  if ( (char *)a1 + (unsigned __int64)v5[2] > Src )
  {
    if ( v6 < 0x10 )
      v8 = v5;
    else
      v8 = *v5;
    return sub_180001C00(v5, v5, Src - v8, Size);
  }
  else
  {
LABEL_13:
    if ( Size == -1i64 )
      std::_Xlength_error("string too long");
    v10 = (size_t)v5[3];
    if ( v10 >= Size )
    {
      if ( !Size )
      {
        v5[2] = 0i64;
        if ( v10 < 0x10 )
        {
          result = v5;
          *(_BYTE *)v5 = 0;
        }
        else
        {
          *(_BYTE *)*v5 = 0;
          return v5;
        }
        return result;
      }
    }
    else
    {
      sub_180001E00((const void **)v5, Size, (size_t)v5[2]);
    }
    if ( Size )
    {
      if ( (unsigned __int64)v5[3] < 0x10 )
        v11 = v5;
      else
        v11 = *v5;
      memcpy(v11, Src, Size);
      v12 = (unsigned __int64)v5[3] < 0x10;
      v5[2] = (void *)Size;
      if ( v12 )
        v13 = v5;
      else
        v13 = *v5;
      v13[Size] = 0;
    }
    return v5;
  }
}
// 180001BA8: conditional instruction was optimized away because rdi.8!=0
// 180006088: using guessed type void __stdcall __noreturn std::_Xlength_error(const char *);

//----- (0000000180001C00) ----------------------------------------------------
void **__fastcall sub_180001C00(void **a1, void **a2, unsigned __int64 a3, size_t a4)
{
  unsigned __int64 v4; // rdi
  void **v6; // rsi
  void **v7; // rbx
  size_t v8; // rdi
  size_t v9; // rax
  bool v10; // cf
  void *v11; // rcx
  void **v12; // rax

  v4 = (unsigned __int64)a2[2];
  v6 = a2;
  v7 = a1;
  if ( v4 < a3 )
  {
    std::_Xout_of_range("invalid string position");
    __debugbreak();
  }
  v8 = v4 - a3;
  if ( a4 < v8 )
    v8 = a4;
  if ( a1 == a2 )
  {
    v9 = v8 + a3;
    if ( (unsigned __int64)a1[2] < v8 + a3 )
    {
      std::_Xout_of_range("invalid string position");
      __debugbreak();
    }
    v10 = (unsigned __int64)a1[3] < 0x10;
    a1[2] = (void *)v9;
    if ( !v10 )
      a1 = (void **)*a1;
    *((_BYTE *)a1 + v9) = 0;
    sub_180001D50(v7, (__int64)a2, a3);
  }
  else if ( sub_180001CE0((const void **)a1, v8) )
  {
    if ( (unsigned __int64)v6[3] >= 0x10 )
      v6 = (void **)*v6;
    if ( (unsigned __int64)v7[3] < 0x10 )
      v11 = v7;
    else
      v11 = *v7;
    if ( v8 )
      memcpy(v11, (char *)v6 + a3, v8);
    v10 = (unsigned __int64)v7[3] < 0x10;
    v7[2] = (void *)v8;
    if ( v10 )
      v12 = v7;
    else
      v12 = (void **)*v7;
    *((_BYTE *)v12 + v8) = 0;
  }
  return v7;
}
// 180006090: using guessed type void __stdcall std::_Xout_of_range(const char *);

//----- (0000000180001CE0) ----------------------------------------------------
bool __fastcall sub_180001CE0(const void **a1, unsigned __int64 a2)
{
  unsigned __int64 v3; // rax

  if ( a2 == -1i64 )
    std::_Xlength_error("string too long");
  v3 = (unsigned __int64)a1[3];
  if ( v3 >= a2 )
  {
    if ( !a2 )
    {
      a1[2] = 0i64;
      if ( v3 >= 0x10 )
        a1 = (const void **)*a1;
      *(_BYTE *)a1 = 0;
    }
    return a2 != 0;
  }
  else
  {
    sub_180001E00(a1, a2, (size_t)a1[2]);
    return a2 != 0;
  }
}
// 180006088: using guessed type void __stdcall __noreturn std::_Xlength_error(const char *);

//----- (0000000180001D50) ----------------------------------------------------
_QWORD *__fastcall sub_180001D50(_QWORD *a1, __int64 a2, unsigned __int64 a3)
{
  unsigned __int64 v3; // rdi
  _QWORD *v4; // rbx
  bool v5; // cf
  size_t v7; // rdi

  v3 = a1[2];
  v4 = a1;
  if ( v3 > a3 )
  {
    if ( a3 )
    {
      if ( a1[3] >= 0x10ui64 )
        a1 = (_QWORD *)*a1;
      v7 = v3 - a3;
      if ( v7 )
        memmove(a1, (char *)a1 + a3, v7);
      v5 = v4[3] < 0x10ui64;
      v4[2] = v7;
      if ( !v5 )
      {
        *(_BYTE *)(*v4 + v7) = 0;
        return v4;
      }
      *((_BYTE *)v4 + v7) = 0;
    }
    return v4;
  }
  else
  {
    v5 = a1[3] < 0x10ui64;
    a1[2] = 0i64;
    if ( v5 )
      *(_BYTE *)a1 = 0;
    else
      *(_BYTE *)*a1 = 0;
    return a1;
  }
}

//----- (0000000180001E00) ----------------------------------------------------
void __fastcall sub_180001E00(const void **Src, unsigned __int64 a2, size_t a3)
{
  const void **v4; // rbx
  unsigned __int64 v5; // rdi
  unsigned __int64 v6; // r8
  unsigned __int64 v7; // rcx
  void *v8; // r14
  const void *v9; // rdx

  v4 = Src;
  v5 = a2 | 0xF;
  if ( (a2 | 0xF) == -1i64 )
  {
    v5 = a2;
  }
  else
  {
    v6 = (unsigned __int64)Src[3];
    v7 = v6 >> 1;
    if ( v6 >> 1 > v5 / 3 )
    {
      v5 = -2i64;
      if ( v6 <= -2i64 - v7 )
        v5 = v7 + v6;
    }
  }
  v8 = 0i64;
  if ( v5 != -1i64 )
  {
    v8 = operator new(v5 + 1);
    if ( !v8 )
      std::_Xbad_alloc();
  }
  if ( a3 )
  {
    if ( (unsigned __int64)v4[3] < 0x10 )
      v9 = v4;
    else
      v9 = *v4;
    memcpy(v8, v9, a3);
  }
  if ( (unsigned __int64)v4[3] >= 0x10 )
    operator delete((void *)*v4);
  *(_BYTE *)v4 = 0;
  *v4 = v8;
  v4[3] = (const void *)v5;
  v4[2] = (const void *)a3;
  if ( v5 >= 0x10 )
    v4 = (const void **)v8;
  *((_BYTE *)v4 + a3) = 0;
}
// 180001E00: could not find valid save-restore pair for rbp
// 180001EC2: conditional instruction was optimized away because rsi.8!=0
// 180006080: using guessed type void std::_Xbad_alloc(void);
// 180006108: using guessed type void __stdcall operator delete(void *);
// 1800061B8: using guessed type void *__stdcall operator new(unsigned __int64);

//----- (0000000180001F10) ----------------------------------------------------
__int64 __fastcall sub_180001F10(__int64 a1, _BYTE *a2)
{
  unsigned int v4; // ebp
  __int64 v5; // rsi
  __int64 v6; // rcx
  __int64 v7; // rbx
  __int64 v8; // rbx
  __int64 v9; // rcx
  __int64 v10; // rcx
  __int64 v11; // rcx
  __int64 v12; // rcx
  __int64 v13; // rcx

  v4 = 0;
  if ( *a2 )
  {
    v5 = -1i64;
    do
      ++v5;
    while ( a2[v5] );
  }
  else
  {
    v5 = 0i64;
  }
  v6 = *(int *)(*(_QWORD *)a1 + 4i64);
  v7 = *(_QWORD *)(v6 + a1 + 40);
  if ( v7 <= 0 || v7 <= v5 )
    v8 = 0i64;
  else
    v8 = v7 - v5;
  v9 = *(_QWORD *)(v6 + a1 + 72);
  if ( v9 )
    (*(void (__fastcall **)(__int64))(*(_QWORD *)v9 + 8i64))(v9);
  v10 = *(int *)(*(_QWORD *)a1 + 4i64);
  if ( !*(_DWORD *)(v10 + a1 + 16) )
  {
    v11 = *(_QWORD *)(v10 + a1 + 80);
    if ( v11 )
      std::ostream::flush(v11, a2);
  }
  v12 = *(int *)(*(_QWORD *)a1 + 4i64);
  if ( *(_DWORD *)(v12 + a1 + 16) )
  {
    v4 = 4;
    goto LABEL_27;
  }
  if ( (*(_DWORD *)(v12 + a1 + 24) & 0x1C0) != 64 && v8 > 0 )
  {
    while ( (unsigned int)std::streambuf::sputc(
                            *(_QWORD *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 72),
                            *(unsigned __int8 *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 88)) != -1 )
    {
      if ( --v8 <= 0 )
        goto LABEL_20;
    }
    goto LABEL_25;
  }
LABEL_20:
  if ( std::streambuf::sputn(*(_QWORD *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 72), a2, v5) != v5 )
  {
LABEL_25:
    v4 = 4;
    goto LABEL_26;
  }
  if ( v8 > 0 )
  {
    while ( (unsigned int)std::streambuf::sputc(
                            *(_QWORD *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 72),
                            *(unsigned __int8 *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 88)) != -1 )
    {
      if ( --v8 <= 0 )
        goto LABEL_26;
    }
    goto LABEL_25;
  }
LABEL_26:
  *(_QWORD *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 40) = 0i64;
LABEL_27:
  std::ios::setstate(a1 + *(int *)(*(_QWORD *)a1 + 4i64), v4, 0i64);
  if ( !std::uncaught_exception() )
    std::ostream::_Osfx(a1);
  v13 = *(_QWORD *)(*(int *)(*(_QWORD *)a1 + 4i64) + a1 + 72);
  if ( v13 )
    (*(void (__fastcall **)(__int64))(*(_QWORD *)v13 + 16i64))(v13);
  return a1;
}
// 180001FA4: variable 'a2' is possibly undefined
// 180006050: using guessed type __int64 __fastcall std::ios::setstate(_QWORD, _QWORD, _QWORD);
// 180006068: using guessed type __int64 __fastcall std::ostream::flush(_QWORD, _QWORD);
// 180006070: using guessed type __int64 __fastcall std::ostream::_Osfx(_QWORD);
// 180006078: using guessed type __int64 __fastcall std::streambuf::sputn(_QWORD, _QWORD, _QWORD);
// 180006098: using guessed type bool std::uncaught_exception(void);
// 1800060B8: using guessed type __int64 __fastcall std::streambuf::sputc(_QWORD, _QWORD);

//----- (00000001800020D0) ----------------------------------------------------
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
  return 1;
}

//----- (00000001800020E0) ----------------------------------------------------
__int64 __fastcall FMC4030_Open_Device(__int64 a1, _BYTE *a2, int a3)
{
  if ( a2 )
    return sub_180001640(a1, a1, a2, a3);
  else
    return 4294967288i64;
}

//----- (0000000180002100) ----------------------------------------------------
__int64 __fastcall FMC4030_Close_Device(__int64 a1)
{
  return sub_180001850(a1, a1);
}

//----- (0000000180002110) ----------------------------------------------------
__int64 __fastcall FMC4030_Jog_Single_Axis(int a1, char a2, float a3, float a4, int a5, int a6, char a7)
{
  _WORD *v9; // rsi
  void *v10; // rbp
  __int64 v11; // rcx

  v9 = operator new[](0x400ui64);
  v10 = operator new[](0x400ui64);
  memset(v9, 0, 0x400ui64);
  *v9 = 1025;
  *((_BYTE *)v9 + 2) = a2;
  *(float *)((char *)v9 + 3) = a3;
  *(float *)((char *)v9 + 7) = a4;
  *(_DWORD *)((char *)v9 + 11) = a5;
  *(_DWORD *)((char *)v9 + 15) = a6;
  *((_BYTE *)v9 + 19) = a7;
  v11 = qword_1800086D8;
  if ( qword_1800086D8 )
  {
    while ( *(_DWORD *)v11 != a1 )
    {
      v11 = *(_QWORD *)(v11 + 40);
      if ( !v11 )
        goto LABEL_7;
    }
    if ( *(_DWORD *)(v11 + 24) == 2 )
      send(*(_QWORD *)(v11 + 32), (const char *)v9, 20, 0);
  }
LABEL_7:
  if ( (unsigned int)sub_1800019B0(v11, a1, (char *)v10, 20) == 20 )
  {
    operator delete[](v9);
    operator delete[](v10);
    return 0i64;
  }
  else
  {
    operator delete[](v9);
    operator delete[](v10);
    return 4294967290i64;
  }
}
// 1800021F7: variable 'v11' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002250) ----------------------------------------------------
__int64 __fastcall FMC4030_Get_Machine_Status(int a1, _DWORD *a2)
{
  _DWORD *v2; // rbx
  _WORD *v5; // r14
  char *v6; // rsi
  __int64 v7; // rcx
  _DWORD *v8; // rdx
  __int64 v9; // rax
  __int128 v10; // xmm0

  v2 = a2;
  if ( !a2 )
    return 4294967288i64;
  v5 = operator new[](0x400ui64);
  v6 = (char *)operator new[](0x400ui64);
  memset(v5, 0, 0x400ui64);
  *v5 = 769;
  v7 = qword_1800086D8;
  if ( qword_1800086D8 )
  {
    while ( *(_DWORD *)v7 != a1 )
    {
      v7 = *(_QWORD *)(v7 + 40);
      if ( !v7 )
        goto LABEL_9;
    }
    if ( *(_DWORD *)(v7 + 24) == 2 )
      send(*(_QWORD *)(v7 + 32), (const char *)v5, 2, 0);
  }
LABEL_9:
  if ( (unsigned int)sub_1800019B0(v7, a1, v6, 664) == 664 )
  {
    if ( (v6[1] | (*v6 << 8)) == 259 )
    {
      v8 = v6 + 4;
      if ( (((unsigned __int8)v2 | (unsigned __int8)((_BYTE)v6 + 4)) & 0xF) != 0 )
      {
        memcpy(v2, v8, 0x294ui64);
      }
      else
      {
        v9 = 5i64;
        do
        {
          v10 = *(_OWORD *)v8;
          v2 += 32;
          v8 += 32;
          *((_OWORD *)v2 - 8) = v10;
          *((_OWORD *)v2 - 7) = *((_OWORD *)v8 - 7);
          *((_OWORD *)v2 - 6) = *((_OWORD *)v8 - 6);
          *((_OWORD *)v2 - 5) = *((_OWORD *)v8 - 5);
          *((_OWORD *)v2 - 4) = *((_OWORD *)v8 - 4);
          *((_OWORD *)v2 - 3) = *((_OWORD *)v8 - 3);
          *((_OWORD *)v2 - 2) = *((_OWORD *)v8 - 2);
          *((_OWORD *)v2 - 1) = *((_OWORD *)v8 - 1);
          --v9;
        }
        while ( v9 );
        *(_OWORD *)v2 = *(_OWORD *)v8;
        v2[4] = v8[4];
      }
      operator delete[](v5);
      operator delete[](v6);
      return 0i64;
    }
    else
    {
      return 0xFFFFFFFFi64;
    }
  }
  else
  {
    operator delete[](v5);
    operator delete[](v6);
    return 4294967290i64;
  }
}
// 1800022F4: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800023F0) ----------------------------------------------------
__int64 __fastcall FMC4030_Get_Device_Para(int a1, __int64 a2)
{
  _WORD *v5; // rbx
  __int64 v6; // rcx
  __int64 v7; // rcx

  if ( !a2 )
    return 4294967288i64;
  v5 = operator new[](0x400ui64);
  memset(v5, 0, 0x400ui64);
  *v5 = 4609;
  v6 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_6;
  while ( *(_DWORD *)v6 != a1 )
  {
    v6 = *(_QWORD *)(v6 + 40);
    if ( !v6 )
      goto LABEL_6;
  }
  if ( *(_DWORD *)(v6 + 24) == 2 && send(*(_QWORD *)(v6 + 32), (const char *)v5, 2, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v7, a1, (char *)v5, 94) == 94 )
    {
      *(_QWORD *)a2 = *(_QWORD *)(v5 + 1);
      *(_QWORD *)(a2 + 8) = *(_QWORD *)(v5 + 5);
      *(_QWORD *)(a2 + 16) = *(_QWORD *)(v5 + 9);
      *(_QWORD *)(a2 + 24) = *(_QWORD *)(v5 + 13);
      *(_QWORD *)(a2 + 32) = *(_QWORD *)(v5 + 17);
      *(_QWORD *)(a2 + 40) = *(_QWORD *)(v5 + 21);
      *(_QWORD *)(a2 + 48) = *(_QWORD *)(v5 + 25);
      *(_QWORD *)(a2 + 56) = *(_QWORD *)(v5 + 29);
      *(_QWORD *)(a2 + 64) = *(_QWORD *)(v5 + 33);
      *(_QWORD *)(a2 + 72) = *(_QWORD *)(v5 + 37);
      *(_QWORD *)(a2 + 80) = *(_QWORD *)(v5 + 41);
      *(_DWORD *)(a2 + 88) = *(_DWORD *)(v5 + 45);
      *(_WORD *)(a2 + 92) = v5[47];
      operator delete[](v5);
      return 0i64;
    }
    else
    {
      operator delete[](v5);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_6:
    operator delete[](v5);
    return 4294967291i64;
  }
}
// 18000249B: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002540) ----------------------------------------------------
__int64 __fastcall FMC4030_Set_Device_Para(int a1, __int64 a2)
{
  _WORD *v5; // rbx
  __int64 v6; // rcx
  __int64 v7; // rcx

  if ( !a2 )
    return 4294967288i64;
  v5 = operator new[](0x400ui64);
  memset(v5, 0, 0x400ui64);
  *v5 = 4865;
  *(_QWORD *)(v5 + 1) = *(_QWORD *)a2;
  *(_QWORD *)(v5 + 5) = *(_QWORD *)(a2 + 8);
  *(_QWORD *)(v5 + 9) = *(_QWORD *)(a2 + 16);
  *(_QWORD *)(v5 + 13) = *(_QWORD *)(a2 + 24);
  *(_QWORD *)(v5 + 17) = *(_QWORD *)(a2 + 32);
  *(_QWORD *)(v5 + 21) = *(_QWORD *)(a2 + 40);
  *(_QWORD *)(v5 + 25) = *(_QWORD *)(a2 + 48);
  *(_QWORD *)(v5 + 29) = *(_QWORD *)(a2 + 56);
  *(_QWORD *)(v5 + 33) = *(_QWORD *)(a2 + 64);
  *(_QWORD *)(v5 + 37) = *(_QWORD *)(a2 + 72);
  *(_QWORD *)(v5 + 41) = *(_QWORD *)(a2 + 80);
  *(_DWORD *)(v5 + 45) = *(_DWORD *)(a2 + 88);
  v6 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_6;
  while ( *(_DWORD *)v6 != a1 )
  {
    v6 = *(_QWORD *)(v6 + 40);
    if ( !v6 )
      goto LABEL_6;
  }
  if ( *(_DWORD *)(v6 + 24) == 2 && send(*(_QWORD *)(v6 + 32), (const char *)v5, 94, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v7, a1, (char *)v5, 94) == 94 )
    {
      operator delete[](v5);
      return 0i64;
    }
    else
    {
      operator delete[](v5);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_6:
    operator delete[](v5);
    return 4294967291i64;
  }
}
// 180002648: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002690) ----------------------------------------------------
__int64 __fastcall FMC4030_Check_Axis_Is_Stop(int a1, int a2)
{
  _BYTE *v4; // rbx
  __int64 v5; // rcx
  __int64 v7; // rcx

  v4 = operator new[](0x400ui64);
  memset(v4, 0, 0x400ui64);
  *(_WORD *)v4 = 1281;
  v4[2] = a2;
  v5 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v5 != a1 )
  {
    v5 = *(_QWORD *)(v5 + 40);
    if ( !v5 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v5 + 24) == 2 && send(*(_QWORD *)(v5 + 32), v4, 3, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v7, a1, v4, 4) == 4 )
    {
      if ( (char)v4[2] == a2 )
      {
        if ( v4[3] )
        {
          operator delete[](v4);
          return 0i64;
        }
        else
        {
          operator delete[](v4);
          return 1i64;
        }
      }
      else
      {
        operator delete[](v4);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v4);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v4);
    return 4294967291i64;
  }
}
// 18000272B: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800027B0) ----------------------------------------------------
__int64 __fastcall FMC4030_Home_Single_Axis(int a1, char a2, float a3, float a4, int a5, char a6)
{
  _WORD *v8; // rdi
  __int64 v9; // rcx
  __int64 v11; // rcx

  v8 = operator new[](0x400ui64);
  memset(v8, 0, 0x400ui64);
  *v8 = 1537;
  *((_BYTE *)v8 + 2) = a2;
  *(float *)((char *)v8 + 3) = a3;
  *(float *)((char *)v8 + 7) = a4;
  *(_DWORD *)((char *)v8 + 11) = a5;
  *((_BYTE *)v8 + 15) = a6;
  v9 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v9 != a1 )
  {
    v9 = *(_QWORD *)(v9 + 40);
    if ( !v9 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v9 + 24) == 2 && send(*(_QWORD *)(v9 + 32), (const char *)v8, 16, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v11, a1, (char *)v8, 16) == 16 )
    {
      operator delete[](v8);
      return 0i64;
    }
    else
    {
      operator delete[](v8);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v8);
    return 4294967291i64;
  }
}
// 18000289F: variable 'v11' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800028D0) ----------------------------------------------------
__int64 __fastcall FMC4030_Stop_Single_Axis(int a1, int a2, char a3)
{
  _BYTE *v6; // rdi
  __int64 v7; // rcx
  __int64 v9; // rcx

  v6 = operator new[](0x400ui64);
  memset(v6, 0, 0x400ui64);
  *(_WORD *)v6 = 1793;
  v6[2] = a2;
  v6[3] = a3;
  v7 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v7 != a1 )
  {
    v7 = *(_QWORD *)(v7 + 40);
    if ( !v7 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v7 + 24) == 2 && send(*(_QWORD *)(v7 + 32), v6, 4, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v9, a1, v6, 4) == 4 )
    {
      if ( (char)v6[2] == a2 )
      {
        operator delete[](v6);
        return 0i64;
      }
      else
      {
        operator delete[](v6);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v6);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v6);
    return 4294967291i64;
  }
}
// 18000297B: variable 'v9' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800029C0) ----------------------------------------------------
__int64 __fastcall FMC4030_Get_Axis_Current_Pos(int a1, char a2, __int64 a3)
{
  _WORD *v7; // rbx
  __int64 v8; // rcx
  __int64 v9; // rcx

  if ( !a3 )
    return 4294967288i64;
  v7 = operator new[](0x400ui64);
  memset(v7, 0, 0x400ui64);
  *v7 = 2049;
  *((_BYTE *)v7 + 2) = a2;
  v8 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_6;
  while ( *(_DWORD *)v8 != a1 )
  {
    v8 = *(_QWORD *)(v8 + 40);
    if ( !v8 )
      goto LABEL_6;
  }
  if ( *(_DWORD *)(v8 + 24) == 2 && send(*(_QWORD *)(v8 + 32), (const char *)v7, 3, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v9, a1, (char *)v7, 7) == 7 )
    {
      *(_DWORD *)a3 = *(_DWORD *)((char *)v7 + 3);
      *(_WORD *)(a3 + 4) = *(_WORD *)((char *)v7 + 7);
      *(_BYTE *)(a3 + 6) = *((_BYTE *)v7 + 9);
      operator delete[](v7);
      return 0i64;
    }
    else
    {
      operator delete[](v7);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_6:
    operator delete[](v7);
    return 4294967291i64;
  }
}
// 180002A81: variable 'v9' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002AC0) ----------------------------------------------------
__int64 __fastcall FMC4030_Get_Axis_Current_Speed(int a1, char a2, __int64 a3)
{
  _WORD *v7; // rbx
  __int64 v8; // rcx
  __int64 v9; // rcx

  if ( !a3 )
    return 4294967288i64;
  v7 = operator new[](0x400ui64);
  memset(v7, 0, 0x400ui64);
  *v7 = 2305;
  *((_BYTE *)v7 + 2) = a2;
  v8 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_6;
  while ( *(_DWORD *)v8 != a1 )
  {
    v8 = *(_QWORD *)(v8 + 40);
    if ( !v8 )
      goto LABEL_6;
  }
  if ( *(_DWORD *)(v8 + 24) == 2 && send(*(_QWORD *)(v8 + 32), (const char *)v7, 3, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v9, a1, (char *)v7, 7) == 7 )
    {
      *(_DWORD *)a3 = *(_DWORD *)((char *)v7 + 3);
      *(_WORD *)(a3 + 4) = *(_WORD *)((char *)v7 + 7);
      *(_BYTE *)(a3 + 6) = *((_BYTE *)v7 + 9);
      operator delete[](v7);
      return 0i64;
    }
    else
    {
      operator delete[](v7);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_6:
    operator delete[](v7);
    return 4294967291i64;
  }
}
// 180002B81: variable 'v9' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002BC0) ----------------------------------------------------
__int64 __fastcall FMC4030_Set_Output(int a1, int a2, char a3)
{
  _BYTE *v6; // rdi
  __int64 v7; // rcx
  __int64 v9; // rcx

  v6 = operator new[](0x400ui64);
  memset(v6, 0, 0x400ui64);
  *(_WORD *)v6 = 2817;
  v6[2] = a2;
  v6[3] = a3;
  v7 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v7 != a1 )
  {
    v7 = *(_QWORD *)(v7 + 40);
    if ( !v7 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v7 + 24) == 2 && send(*(_QWORD *)(v7 + 32), v6, 4, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v9, a1, v6, 4) == 4 )
    {
      if ( (char)v6[2] == a2 )
      {
        operator delete[](v6);
        return 0i64;
      }
      else
      {
        operator delete[](v6);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v6);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v6);
    return 4294967291i64;
  }
}
// 180002C6B: variable 'v9' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002CB0) ----------------------------------------------------
__int64 __fastcall FMC4030_Get_Input(int a1, int a2, _DWORD *a3)
{
  _BYTE *v7; // rbx
  __int64 v8; // rcx
  __int64 v9; // rcx

  if ( !a3 )
    return 4294967288i64;
  v7 = operator new[](0x400ui64);
  memset(v7, 0, 0x400ui64);
  *(_WORD *)v7 = 3073;
  v7[2] = a2;
  v8 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_6;
  while ( *(_DWORD *)v8 != a1 )
  {
    v8 = *(_QWORD *)(v8 + 40);
    if ( !v8 )
      goto LABEL_6;
  }
  if ( *(_DWORD *)(v8 + 24) == 2 && send(*(_QWORD *)(v8 + 32), v7, 3, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v9, a1, v7, 3) == 3 )
    {
      if ( (char)v7[2] == a2 )
      {
        *a3 = (char)v7[3];
        operator delete[](v7);
        return 0i64;
      }
      else
      {
        operator delete[](v7);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v7);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_6:
    operator delete[](v7);
    return 4294967291i64;
  }
}
// 180002D71: variable 'v9' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002DB0) ----------------------------------------------------
__int64 __fastcall FMC4030_Write_Data_To_485(int a1, const void *a2, int a3)
{
  size_t v3; // rdi
  _WORD *v7; // rbx
  int v8; // edi
  __int64 v9; // rcx
  __int64 v10; // rcx

  v3 = a3;
  if ( !a2 )
    return 4294967288i64;
  if ( a3 > 1018 )
    return 4294967286i64;
  v7 = operator new[](0x400ui64);
  memset(v7, 0, 0x400ui64);
  *v7 = 3329;
  *(_DWORD *)(v7 + 1) = v3;
  memcpy(v7 + 3, a2, v3);
  v8 = v3 + 6;
  if ( (unsigned int)sub_180001940(v9, a1, (const char *)v7, v8) )
  {
    operator delete[](v7);
    return 4294967291i64;
  }
  else if ( (unsigned int)sub_1800019B0(v10, a1, (char *)v7, v8) == v8 )
  {
    operator delete[](v7);
    return 0i64;
  }
  else
  {
    operator delete[](v7);
    return 4294967290i64;
  }
}
// 180002E41: variable 'v9' is possibly undefined
// 180002E62: variable 'v10' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);

//----- (0000000180002EA0) ----------------------------------------------------
__int64 __fastcall FMC4030_Read_Data_From_485(int a1, void *a2, int *a3)
{
  _WORD *v6; // rbx
  __int64 v7; // rcx
  __int64 v9; // rcx
  size_t v10; // r8

  if ( !a2 || !a3 )
    return 4294967288i64;
  v6 = operator new[](0x400ui64);
  memset(v6, 0, 0x400ui64);
  *v6 = 3585;
  v7 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_6;
  while ( *(_DWORD *)v7 != a1 )
  {
    v7 = *(_QWORD *)(v7 + 40);
    if ( !v7 )
      goto LABEL_6;
  }
  if ( *(_DWORD *)(v7 + 24) == 2 && send(*(_QWORD *)(v7 + 32), (const char *)v6, 1024, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v9, a1, (char *)v6, 1024) == 1024 )
    {
      v10 = *(int *)(v6 + 1);
      *a3 = v10;
      memcpy(a2, v6 + 3, v10);
      *((_BYTE *)a2 + *a3) = 0;
      operator delete[](v6);
      return 0i64;
    }
    else
    {
      operator delete[](v6);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_6:
    operator delete[](v6);
    return 4294967291i64;
  }
}
// 180002F5C: variable 'v9' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180002FC0) ----------------------------------------------------
__int64 __fastcall FMC4030_Line_2Axis(int a1, int a2, float a3, float a4, int a5, int a6, int a7)
{
  _WORD *v9; // rbx
  __int64 v10; // rcx
  __int64 v12; // rcx

  v9 = operator new[](0x400ui64);
  memset(v9, 0, 0x400ui64);
  *v9 = 3841;
  *((_BYTE *)v9 + 2) = a2;
  *(float *)((char *)v9 + 3) = a3;
  *(float *)((char *)v9 + 7) = a4;
  *(_DWORD *)((char *)v9 + 11) = a5;
  *(_DWORD *)((char *)v9 + 15) = a6;
  *(_DWORD *)((char *)v9 + 19) = a7;
  v10 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v10 != a1 )
  {
    v10 = *(_QWORD *)(v10 + 40);
    if ( !v10 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v10 + 24) == 2 && send(*(_QWORD *)(v10 + 32), (const char *)v9, 23, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v12, a1, (char *)v9, 23) == 23 )
    {
      if ( *((char *)v9 + 2) == a2 )
      {
        operator delete[](v9);
        return 0i64;
      }
      else
      {
        operator delete[](v9);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v9);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v9);
    return 4294967291i64;
  }
}
// 1800030CF: variable 'v12' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003110) ----------------------------------------------------
__int64 __fastcall FMC4030_Line_3Axis(int a1, int a2, float a3, float a4, int a5, int a6, int a7, int a8)
{
  _WORD *v10; // rbx
  __int64 v11; // rcx
  __int64 v13; // rcx

  v10 = operator new[](0x400ui64);
  memset(v10, 0, 0x400ui64);
  *v10 = 4353;
  *((_BYTE *)v10 + 2) = a2;
  *(float *)((char *)v10 + 3) = a3;
  *(float *)((char *)v10 + 7) = a4;
  *(_DWORD *)((char *)v10 + 11) = a5;
  *(_DWORD *)((char *)v10 + 15) = a6;
  *(_DWORD *)((char *)v10 + 19) = a7;
  *(_DWORD *)((char *)v10 + 23) = a8;
  v11 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v11 != a1 )
  {
    v11 = *(_QWORD *)(v11 + 40);
    if ( !v11 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v11 + 24) == 2 && send(*(_QWORD *)(v11 + 32), (const char *)v10, 27, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v13, a1, (char *)v10, 27) == 27 )
    {
      if ( *((char *)v10 + 2) == a2 )
      {
        operator delete[](v10);
        return 0i64;
      }
      else
      {
        operator delete[](v10);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v10);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v10);
    return 4294967291i64;
  }
}
// 180003231: variable 'v13' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003270) ----------------------------------------------------
__int64 __fastcall FMC4030_Arc_2Axis(
        int a1,
        int a2,
        float a3,
        float a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        char a11)
{
  _WORD *v13; // rbx
  __int64 v14; // rcx
  __int64 v16; // rcx

  v13 = operator new[](0x400ui64);
  memset(v13, 0, 0x400ui64);
  *v13 = 4097;
  *((_BYTE *)v13 + 2) = a2;
  *(float *)((char *)v13 + 3) = a3;
  *(float *)((char *)v13 + 7) = a4;
  *(_DWORD *)((char *)v13 + 11) = a5;
  *(_DWORD *)((char *)v13 + 15) = a6;
  *(_DWORD *)((char *)v13 + 19) = a7;
  *(_DWORD *)((char *)v13 + 23) = a8;
  *(_DWORD *)((char *)v13 + 27) = a9;
  *(_DWORD *)((char *)v13 + 31) = a10;
  *((_BYTE *)v13 + 35) = a11;
  v14 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v14 != a1 )
  {
    v14 = *(_QWORD *)(v14 + 40);
    if ( !v14 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v14 + 24) == 2 && send(*(_QWORD *)(v14 + 32), (const char *)v13, 36, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v16, a1, (char *)v13, 36) == 36 )
    {
      if ( *((char *)v13 + 2) == a2 )
      {
        operator delete[](v13);
        return 0i64;
      }
      else
      {
        operator delete[](v13);
        return 4294967289i64;
      }
    }
    else
    {
      operator delete[](v13);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v13);
    return 4294967291i64;
  }
}
// 1800033CF: variable 'v16' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003410) ----------------------------------------------------
__int64 __fastcall FMC4030_Pause_Run(int a1, char a2)
{
  _BYTE *v4; // rdi
  __int64 v5; // rcx
  __int64 v7; // rcx

  v4 = operator new[](0x400ui64);
  memset(v4, 0, 0x400ui64);
  *(_WORD *)v4 = 6401;
  v4[2] = a2;
  v5 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v5 != a1 )
  {
    v5 = *(_QWORD *)(v5 + 40);
    if ( !v5 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v5 + 24) == 2 && send(*(_QWORD *)(v5 + 32), v4, 3, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v7, a1, v4, 3) == 3 )
    {
      operator delete[](v4);
      return 0i64;
    }
    else
    {
      operator delete[](v4);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v4);
    return 4294967291i64;
  }
}
// 1800034AA: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800034F0) ----------------------------------------------------
__int64 __fastcall FMC4030_Resume_Run(int a1, char a2)
{
  _BYTE *v4; // rdi
  __int64 v5; // rcx
  __int64 v7; // rcx

  v4 = operator new[](0x400ui64);
  memset(v4, 0, 0x400ui64);
  *(_WORD *)v4 = 6657;
  v4[2] = a2;
  v5 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v5 != a1 )
  {
    v5 = *(_QWORD *)(v5 + 40);
    if ( !v5 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v5 + 24) == 2 && send(*(_QWORD *)(v5 + 32), v4, 3, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v7, a1, v4, 3) == 3 )
    {
      operator delete[](v4);
      return 0i64;
    }
    else
    {
      operator delete[](v4);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v4);
    return 4294967291i64;
  }
}
// 18000358A: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800035D0) ----------------------------------------------------
__int64 FMC4030_Stop_Run()
{
  return 0i64;
}

//----- (00000001800035E0) ----------------------------------------------------
__int64 __fastcall FMC4030_Download_File(int a1, const char *a2, int a3)
{
  _DWORD *v6; // rsi
  size_t v7; // rbx
  __int64 v8; // rcx
  int v9; // edx
  __int64 v10; // rax
  int v12; // r13d
  char v13; // di
  char v14; // r14
  char v15; // r15
  __int64 v16; // rcx
  __int64 v17; // rcx
  __int64 v18; // rcx
  __int64 v19; // rcx
  void *v20; // rcx
  __int64 v21; // rcx
  __int64 v22; // rbx
  int v23; // edi
  int v24; // eax
  __int64 v25; // rcx
  __int64 v26; // rcx
  FILE *Stream; // [rsp+28h] [rbp-60h] BYREF
  __int64 Src[3]; // [rsp+30h] [rbp-58h] BYREF
  int v29; // [rsp+48h] [rbp-40h]
  __int16 v30; // [rsp+4Ch] [rbp-3Ch]

  Stream = 0i64;
  v6 = operator new[](0x400ui64);
  memset(v6, 0, 0x400ui64);
  v7 = -1i64;
  memset(Src, 0, sizeof(Src));
  v29 = 0;
  v30 = 0;
  if ( a2 )
  {
    v8 = -1i64;
    do
      ++v8;
    while ( a2[v8] );
    v9 = v8;
    v10 = (int)v8;
    if ( (_DWORD)v8 )
    {
      while ( 1 )
      {
        --v10;
        LODWORD(v8) = v8 - 1;
        if ( a2[v10 - 1] == 47 )
          break;
        if ( !v10 )
          goto LABEL_7;
      }
    }
    else
    {
LABEL_7:
      LODWORD(v8) = v8 - 1;
    }
    memcpy(Src, &a2[(int)v8], v9 - (int)v8 + 1);
  }
  if ( fopen_s(&Stream, a2, "rb") )
  {
    operator delete[](v6);
    return 4294967287i64;
  }
  fseek(Stream, 0, 2);
  v12 = ftell(Stream);
  fseek(Stream, 0, 0);
  v13 = HIBYTE(v12);
  v14 = BYTE2(v12);
  v15 = BYTE1(v12);
  if ( a3 == 1 )
  {
    *v6 = 16847873;
    v6[1] = v12;
    v16 = qword_1800086D8;
    if ( qword_1800086D8 )
    {
      while ( *(_DWORD *)v16 != a1 )
      {
        v16 = *(_QWORD *)(v16 + 40);
        if ( !v16 )
          goto LABEL_26;
      }
      if ( *(_DWORD *)(v16 + 24) == 2 && send(*(_QWORD *)(v16 + 32), (const char *)v6, 8, 0) != -1 )
      {
        if ( (unsigned int)sub_1800019B0(v17, a1, (char *)v6, 8) != 8 )
        {
LABEL_19:
          operator delete[](v6);
          return 4294967290i64;
        }
        goto LABEL_30;
      }
    }
LABEL_26:
    operator delete[](v6);
    return 4294967291i64;
  }
  if ( a3 == 2 )
  {
    *v6 = 33625089;
    v6[1] = v12;
    do
      ++v7;
    while ( *((_BYTE *)Src + v7) );
    memcpy(v6 + 2, Src, v7);
    v18 = qword_1800086D8;
    if ( !qword_1800086D8 )
      goto LABEL_26;
    while ( *(_DWORD *)v18 != a1 )
    {
      v18 = *(_QWORD *)(v18 + 40);
      if ( !v18 )
        goto LABEL_26;
    }
    if ( *(_DWORD *)(v18 + 24) != 2 || send(*(_QWORD *)(v18 + 32), (const char *)v6, v7 + 8, 0) == -1 )
      goto LABEL_26;
    if ( (int)sub_1800019B0(v19, a1, (char *)v6, (int)v7 + 8) != v7 + 8 )
      goto LABEL_19;
  }
LABEL_30:
  if ( !v12 )
    goto LABEL_57;
  while ( 1 )
  {
    v20 = v6 + 2;
    if ( v12 <= 1000 )
      break;
    *((_BYTE *)v6 + 2) = 2;
    v6[1] = 1000;
    fread(v20, 1ui64, 0x3E8ui64, Stream);
    v21 = qword_1800086D8;
    v12 -= 1000;
    if ( !qword_1800086D8 )
      goto LABEL_35;
    while ( *(_DWORD *)v21 != a1 )
    {
      v21 = *(_QWORD *)(v21 + 40);
      if ( !v21 )
        goto LABEL_35;
    }
    if ( *(_DWORD *)(v21 + 24) != 2 || send(*(_QWORD *)(v21 + 32), (const char *)v6, 1008, 0) == -1 )
      goto LABEL_35;
    v22 = qword_1800086D8;
    v23 = 0;
    if ( !qword_1800086D8 )
      goto LABEL_56;
    while ( *(_DWORD *)v22 != a1 )
    {
      v22 = *(_QWORD *)(v22 + 40);
      if ( !v22 )
        goto LABEL_56;
    }
    if ( *(_DWORD *)(v22 + 24) != 2 )
      goto LABEL_56;
    v24 = recv(*(_QWORD *)(v22 + 32), (char *)v6, 1008, 0);
    if ( v24 == -1 )
      goto LABEL_56;
    while ( 1 )
    {
      v23 += v24;
      if ( v23 == 1008 )
        break;
      v24 = recv(*(_QWORD *)(v22 + 32), (char *)v6 + v23, 1008, 0);
      if ( v24 == -1 )
        goto LABEL_56;
    }
    if ( !v12 )
      goto LABEL_57;
    v13 = HIBYTE(v12);
    v14 = BYTE2(v12);
    v15 = BYTE1(v12);
  }
  *((_BYTE *)v6 + 2) = 3;
  *((_BYTE *)v6 + 4) = v12;
  *((_BYTE *)v6 + 5) = v15;
  *((_BYTE *)v6 + 6) = v14;
  *((_BYTE *)v6 + 7) = v13;
  fread(v20, 1ui64, v12, Stream);
  v25 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_35;
  while ( *(_DWORD *)v25 != a1 )
  {
    v25 = *(_QWORD *)(v25 + 40);
    if ( !v25 )
      goto LABEL_35;
  }
  if ( *(_DWORD *)(v25 + 24) != 2 || send(*(_QWORD *)(v25 + 32), (const char *)v6, v12 + 8, 0) == -1 )
  {
LABEL_35:
    operator delete[](v6);
    fclose(Stream);
    return 4294967291i64;
  }
  if ( (unsigned int)sub_1800019B0(v26, a1, (char *)v6, v12 + 8) == v12 + 8 )
  {
LABEL_57:
    operator delete[](v6);
    fclose(Stream);
    return 0i64;
  }
  else
  {
LABEL_56:
    operator delete[](v6);
    fclose(Stream);
    return 4294967290i64;
  }
}
// 18000378A: variable 'v17' is possibly undefined
// 180003850: variable 'v19' is possibly undefined
// 180003A34: variable 'v26' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003AA0) ----------------------------------------------------
__int64 __fastcall FMC4030_Start_Auto_Run(int a1, _BYTE *a2)
{
  _WORD *v4; // rsi
  __int64 v5; // rbx
  size_t v6; // r8
  __int64 v7; // rax
  bool v8; // zf
  __int64 v9; // rcx
  __int64 v11; // rcx
  __int64 v12; // rax
  int v13; // eax

  v4 = operator new[](0x400ui64);
  memset(v4, 0, 0x400ui64);
  v5 = -1i64;
  *v4 = 5377;
  v6 = -1i64;
  do
    ++v6;
  while ( a2[v6] );
  memcpy(v4 + 1, a2, v6);
  v7 = -1i64;
  do
    v8 = a2[++v7] == 0;
  while ( !v8 );
  v9 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_8;
  while ( *(_DWORD *)v9 != a1 )
  {
    v9 = *(_QWORD *)(v9 + 40);
    if ( !v9 )
      goto LABEL_8;
  }
  if ( *(_DWORD *)(v9 + 24) == 2 && send(*(_QWORD *)(v9 + 32), (const char *)v4, v7 + 2, 0) != -1 )
  {
    v12 = -1i64;
    do
      v8 = a2[++v12] == 0;
    while ( !v8 );
    v13 = sub_1800019B0(v11, a1, (char *)v4, (int)v12 + 2);
    do
      ++v5;
    while ( a2[v5] );
    if ( v13 == v5 + 2 )
    {
      operator delete[](v4);
      return 0i64;
    }
    else
    {
      operator delete[](v4);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_8:
    operator delete[](v4);
    return 4294967291i64;
  }
}
// 180003B84: variable 'v11' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003BD0) ----------------------------------------------------
__int64 __fastcall FMC4030_Stop_Auto_Run(int a1)
{
  _WORD *v2; // rbx
  __int64 v3; // rcx
  __int64 v5; // rcx

  v2 = operator new[](0x400ui64);
  memset(v2, 0, 0x400ui64);
  *v2 = 5633;
  v3 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v3 != a1 )
  {
    v3 = *(_QWORD *)(v3 + 40);
    if ( !v3 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v3 + 24) == 2 && send(*(_QWORD *)(v3 + 32), (const char *)v2, 2, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v5, a1, (char *)v2, 2) == 2 )
    {
      operator delete[](v2);
      return 0i64;
    }
    else
    {
      operator delete[](v2);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v2);
    return 4294967291i64;
  }
}
// 180003C60: variable 'v5' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003CA0) ----------------------------------------------------
__int64 __fastcall FMC4030_Delete_Script_File(int a1, _BYTE *a2)
{
  _WORD *v4; // rsi
  __int64 v5; // rbx
  size_t v6; // r8
  __int64 v7; // rax
  bool v8; // zf
  __int64 v9; // rcx
  __int64 v11; // rcx
  __int64 v12; // rax
  int v13; // eax

  v4 = operator new[](0x400ui64);
  memset(v4, 0, 0x400ui64);
  v5 = -1i64;
  *v4 = 6145;
  v6 = -1i64;
  do
    ++v6;
  while ( a2[v6] );
  memcpy(v4 + 1, a2, v6);
  v7 = -1i64;
  do
    v8 = a2[++v7] == 0;
  while ( !v8 );
  v9 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_8;
  while ( *(_DWORD *)v9 != a1 )
  {
    v9 = *(_QWORD *)(v9 + 40);
    if ( !v9 )
      goto LABEL_8;
  }
  if ( *(_DWORD *)(v9 + 24) == 2 && send(*(_QWORD *)(v9 + 32), (const char *)v4, v7 + 2, 0) != -1 )
  {
    v12 = -1i64;
    do
      v8 = a2[++v12] == 0;
    while ( !v8 );
    v13 = sub_1800019B0(v11, a1, (char *)v4, (int)v12 + 2);
    do
      ++v5;
    while ( a2[v5] );
    if ( v13 == v5 + 2 )
    {
      operator delete[](v4);
      return 0i64;
    }
    else
    {
      operator delete[](v4);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_8:
    operator delete[](v4);
    return 4294967291i64;
  }
}
// 180003D84: variable 'v11' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003DD0) ----------------------------------------------------
__int64 __fastcall FMC4030_Get_Version_Info(int a1, __int64 a2)
{
  _WORD *v4; // rbx
  __int64 v5; // rcx
  __int64 v7; // rcx
  int v8; // eax
  __int64 v9; // [rsp+20h] [rbp-18h]

  v4 = operator new[](0x400ui64);
  memset(v4, 0, 0x400ui64);
  *v4 = 5889;
  v5 = qword_1800086D8;
  HIDWORD(v9) = 20220329;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v5 != a1 )
  {
    v5 = *(_QWORD *)(v5 + 40);
    if ( !v5 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v5 + 24) == 2 && send(*(_QWORD *)(v5 + 32), (const char *)v4, 2, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v7, a1, (char *)v4, 10) == 10 )
    {
      LODWORD(v9) = *(_DWORD *)(v4 + 1);
      v8 = *(_DWORD *)(v4 + 3);
      *(_QWORD *)a2 = v9;
      *(_DWORD *)(a2 + 8) = v8;
      operator delete[](v4);
      return 0i64;
    }
    else
    {
      operator delete[](v4);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v4);
    return 4294967291i64;
  }
}
// 180003E75: variable 'v7' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180003ED0) ----------------------------------------------------
__int64 __fastcall FMC4030_MB03_Operation(int a1, unsigned __int8 a2, __int16 a3, int a4, void *a5, _DWORD *a6)
{
  unsigned __int8 *v10; // rsi
  __int16 v11; // ax
  __int64 v12; // rcx
  __int64 v14; // rcx
  size_t v15; // rax

  v10 = (unsigned __int8 *)operator new[](0x400ui64);
  memset(v10, 0, 0x400ui64);
  v10[4] = HIBYTE(a3);
  *(_WORD *)v10 = 7169;
  v10[2] = a2;
  v10[3] = 3;
  v10[5] = a3;
  v10[6] = BYTE1(a4);
  v10[7] = a4;
  v11 = sub_1800043F0(v10 + 2, 6u);
  v10[9] = v11;
  v10[8] = HIBYTE(v11);
  v12 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v12 != a1 )
  {
    v12 = *(_QWORD *)(v12 + 40);
    if ( !v12 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v12 + 24) == 2 && send(*(_QWORD *)(v12 + 32), (const char *)v10, 10, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v14, a1, (char *)v10, 2 * a4 + 8) == 2 * a4 + 8 )
    {
      if ( a5 )
      {
        if ( a6 )
        {
          v15 = (char)v10[2];
          *a6 = v15;
          memcpy(a5, v10 + 3, v15);
        }
      }
      operator delete[](v10);
      return 0i64;
    }
    else
    {
      operator delete[](v10);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v10);
    return 4294967291i64;
  }
}
// 180003FCE: variable 'v14' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180004020) ----------------------------------------------------
__int64 __fastcall FMC4030_MB05_Operation(int a1, unsigned __int8 a2, __int16 a3, __int16 a4, void *a5, _DWORD *a6)
{
  unsigned __int8 *v10; // r14
  __int16 v11; // ax
  __int64 v12; // rcx
  __int64 v14; // rcx
  size_t v15; // rax

  v10 = (unsigned __int8 *)operator new[](0x400ui64);
  memset(v10, 0, 0x400ui64);
  *(_WORD *)v10 = 7425;
  v10[2] = a2;
  v10[3] = 5;
  v10[5] = a3;
  v10[4] = HIBYTE(a3);
  if ( a4 )
    *((_WORD *)v10 + 3) = 255;
  else
    *((_WORD *)v10 + 3) = 0;
  v11 = sub_1800043F0(v10 + 2, 6u);
  v10[9] = v11;
  v10[8] = HIBYTE(v11);
  v12 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_7;
  while ( *(_DWORD *)v12 != a1 )
  {
    v12 = *(_QWORD *)(v12 + 40);
    if ( !v12 )
      goto LABEL_7;
  }
  if ( *(_DWORD *)(v12 + 24) == 2 && send(*(_QWORD *)(v12 + 32), (const char *)v10, 10, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v14, a1, (char *)v10, 11) == 11 )
    {
      if ( a5 )
      {
        if ( a6 )
        {
          v15 = (char)v10[2];
          *a6 = v15;
          memcpy(a5, v10 + 3, v15);
        }
      }
      operator delete[](v10);
      return 0i64;
    }
    else
    {
      operator delete[](v10);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_7:
    operator delete[](v10);
    return 4294967291i64;
  }
}
// 18000411E: variable 'v14' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (0000000180004170) ----------------------------------------------------
__int64 __fastcall FMC4030_MB06_Operation(int a1, unsigned __int8 a2, __int16 a3, __int16 a4, void *a5, _DWORD *a6)
{
  unsigned __int8 *v10; // r14
  __int16 v11; // ax
  __int64 v12; // rcx
  __int64 v14; // rcx
  size_t v15; // rax

  v10 = (unsigned __int8 *)operator new[](0x400ui64);
  memset(v10, 0, 0x400ui64);
  v10[4] = HIBYTE(a3);
  *(_WORD *)v10 = 7681;
  v10[2] = a2;
  v10[3] = 6;
  v10[5] = a3;
  v10[6] = HIBYTE(a4);
  v10[7] = a4;
  v11 = sub_1800043F0(v10 + 2, 6u);
  v10[9] = v11;
  v10[8] = HIBYTE(v11);
  v12 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v12 != a1 )
  {
    v12 = *(_QWORD *)(v12 + 40);
    if ( !v12 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v12 + 24) == 2 && send(*(_QWORD *)(v12 + 32), (const char *)v10, 10, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v14, a1, (char *)v10, 11) == 11 )
    {
      if ( a5 )
      {
        if ( a6 )
        {
          v15 = (char)v10[2];
          *a6 = v15;
          memcpy(a5, v10 + 3, v15);
        }
      }
      operator delete[](v10);
      return 0i64;
    }
    else
    {
      operator delete[](v10);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v10);
    return 4294967291i64;
  }
}
// 180004266: variable 'v14' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800042C0) ----------------------------------------------------
__int64 __fastcall FMC4030_MB16_Operation(int a1, char a2, __int16 a3, int a4, __int64 a5, void *a6, _DWORD *a7)
{
  char *v11; // rbp
  __int64 v12; // rcx
  int v13; // eax
  __int64 v14; // rcx
  __int64 v16; // rcx
  size_t v17; // rax

  v11 = (char *)operator new[](0x400ui64);
  memset(v11, 0, 0x400ui64);
  v13 = sub_180001000(v12, (__int64)v11, a2, a3, a5, a4);
  v14 = qword_1800086D8;
  if ( !qword_1800086D8 )
    goto LABEL_4;
  while ( *(_DWORD *)v14 != a1 )
  {
    v14 = *(_QWORD *)(v14 + 40);
    if ( !v14 )
      goto LABEL_4;
  }
  if ( *(_DWORD *)(v14 + 24) == 2 && send(*(_QWORD *)(v14 + 32), v11, v13, 0) != -1 )
  {
    if ( (unsigned int)sub_1800019B0(v16, a1, v11, 11) == 11 )
    {
      if ( a6 )
      {
        if ( a7 )
        {
          v17 = v11[2];
          *a7 = v17;
          memcpy(a6, v11 + 3, v17);
        }
      }
      operator delete[](v11);
      return 0i64;
    }
    else
    {
      operator delete[](v11);
      return 4294967290i64;
    }
  }
  else
  {
LABEL_4:
    operator delete[](v11);
    return 4294967291i64;
  }
}
// 18000431C: variable 'v12' is possibly undefined
// 180004391: variable 'v16' is possibly undefined
// 1800061A0: using guessed type void __stdcall operator delete[](void *);
// 1800061A8: using guessed type void *__stdcall operator new[](unsigned __int64);
// 1800086D8: using guessed type __int64 qword_1800086D8;

//----- (00000001800043F0) ----------------------------------------------------
__int64 __fastcall sub_1800043F0(unsigned __int8 *a1, unsigned int a2)
{
  __int16 v2; // ax
  __int64 v3; // r8
  unsigned __int8 v4; // dl
  unsigned __int16 v5; // ax
  unsigned __int16 v6; // ax
  unsigned __int16 v7; // ax
  unsigned __int16 v8; // ax
  unsigned __int16 v9; // ax
  unsigned __int16 v10; // ax
  unsigned __int16 v11; // ax
  unsigned __int16 v12; // ax

  v2 = -1;
  if ( a2 )
  {
    v3 = a2;
    do
    {
      v4 = *a1++;
      v5 = v4 ^ v2;
      if ( (v5 & 1) != 0 )
        v6 = (v5 >> 1) ^ 0xA001;
      else
        v6 = v5 >> 1;
      if ( (v6 & 1) != 0 )
        v7 = (v6 >> 1) ^ 0xA001;
      else
        v7 = v6 >> 1;
      if ( (v7 & 1) != 0 )
        v8 = (v7 >> 1) ^ 0xA001;
      else
        v8 = v7 >> 1;
      if ( (v8 & 1) != 0 )
        v9 = (v8 >> 1) ^ 0xA001;
      else
        v9 = v8 >> 1;
      if ( (v9 & 1) != 0 )
        v10 = (v9 >> 1) ^ 0xA001;
      else
        v10 = v9 >> 1;
      if ( (v10 & 1) != 0 )
        v11 = (v10 >> 1) ^ 0xA001;
      else
        v11 = v10 >> 1;
      if ( (v11 & 1) != 0 )
        v12 = (v11 >> 1) ^ 0xA001;
      else
        v12 = v11 >> 1;
      if ( (v12 & 1) != 0 )
        v2 = (v12 >> 1) ^ 0xA001;
      else
        v2 = v12 >> 1;
      --v3;
    }
    while ( v3 );
  }
  return HIBYTE(v2) | ((unsigned __int8)v2 << 8);
}

//----- (0000000180004E28) ----------------------------------------------------
void sub_180004E28()
{
  void (**i)(void); // rbx

  for ( i = qword_1800068B8; i < qword_1800068B8; ++i )
  {
    if ( *i )
      (*i)();
  }
}
// 1800068B8: using guessed type void (*qword_1800068B8[2])(void);

//----- (0000000180004E60) ----------------------------------------------------
void __fastcall sub_180004E60()
{
  void (**i)(void); // rbx

  for ( i = &qword_1800068C8; i < &qword_1800068C8; ++i )
  {
    if ( *i )
      (*i)();
  }
}
// 1800068C8: using guessed type void (*qword_1800068C8)(void);

//----- (0000000180004EA4) ----------------------------------------------------
void __fastcall sub_180004EA4()
{
  _clean_type_info_names_internal(&unk_1800086B8);
}
// 180004ED4: using guessed type __int64 __fastcall _clean_type_info_names_internal(_QWORD);

//----- (0000000180005120) ----------------------------------------------------
int sub_180005120()
{
  return atexit((void (__cdecl *)())sub_1800051A0);
}

//----- (0000000180005130) ----------------------------------------------------
int sub_180005130()
{
  return atexit((void (__cdecl *)())sub_180005190);
}

//----- (0000000180005140) ----------------------------------------------------
int sub_180005140()
{
  return atexit((void (__cdecl *)())sub_180005180);
}

//----- (0000000180005150) ----------------------------------------------------
int sub_180005150()
{
  return atexit((void (__cdecl *)())sub_1800051B0);
}

//----- (0000000180005160) ----------------------------------------------------
int sub_180005160()
{
  return atexit((void (__cdecl *)())nullsub_1);
}
// 1800051C0: using guessed type __int64 __fastcall nullsub_1();

//----- (0000000180005170) ----------------------------------------------------
int sub_180005170()
{
  return atexit((void (__cdecl *)())nullsub_2);
}
// 1800051D0: using guessed type __int64 __fastcall nullsub_2();

//----- (0000000180005180) ----------------------------------------------------
void **sub_180005180()
{
  void **result; // rax

  result = &std::error_category::`vftable';
  off_180008120 = (__int64 (__fastcall **)())&std::error_category::`vftable';
  return result;
}
// 1800064C8: using guessed type void *std::error_category::`vftable';
// 180008120: using guessed type __int64 (__fastcall **off_180008120)();

//----- (0000000180005190) ----------------------------------------------------
void **sub_180005190()
{
  void **result; // rax

  result = &std::error_category::`vftable';
  off_180008118[0] = (__int64 (__fastcall **)())&std::error_category::`vftable';
  return result;
}
// 1800064C8: using guessed type void *std::error_category::`vftable';
// 180008118: using guessed type __int64 (__fastcall **off_180008118[2])();

//----- (00000001800051A0) ----------------------------------------------------
void **sub_1800051A0()
{
  void **result; // rax

  result = &std::error_category::`vftable';
  off_180008110[0] = (__int64 (__fastcall **)())&std::error_category::`vftable';
  return result;
}
// 1800064C8: using guessed type void *std::error_category::`vftable';
// 180008110: using guessed type __int64 (__fastcall **off_180008110[3])();

// nfuncs=113 queued=68 decompiled=68 lumina nreq=0 worse=0 better=0
// ALL OK, 68 function(s) have been successfully decompiled
